Feature/token gated chat use case
LiveLike/engagement-sample-app pull request #29
Opened 2022-05-17 21:14 UTC by mmoloksher

Add a Token Gated Chat Use Case
Accompanying docs can be found here... https://github.com/LiveLike/engagement-sample-app/wiki/Token-Gated-Chat-Tutorial

2022-05-17 23:12 UTC, mjelzon requested changes

2022-05-17 23:12 UTC, mjelzon commented on Sample App/Use Cases/Token Gated Chat/TokenGatedChatUseCase.swift
> +                        apiKey: "<API KEY>"
Should you add a text field for the user to input an api key. The person checking out this use case may not be a developer and won't have a means to change this.

2022-05-17 23:17 UTC, mmoloksher commented on Sample App/Use Cases/Token Gated Chat/TokenGatedChatUseCase.swift
> +                        apiKey: "<API KEY>"
Not sure if necessary. This use case goes hand in hand with the tutorial, it's meant strictly for integrators.

2022-05-17 23:19 UTC, mjelzon commented on Sample App/Use Cases/Token Gated Chat/TokenGatedChatUseCase.swift
> +                        apiKey: "<API KEY>"
I'm not seeing anywhere in the docs saying this needs to be replaced with an actual token. Could be missed.

2022-05-19 18:53 UTC, mmoloksher commented on Sample App/Use Cases/Token Gated Chat/TokenGatedChatUseCase.swift
> +                        apiKey: "<API KEY>"
good point, ill add to the docs

2022-05-19 19:01 UTC, mmoloksher commented on Sample App/Use Cases/Token Gated Chat/TokenGatedChatUseCase.swift
> +                        apiKey: "<API KEY>"
@mjelzon  added more instructions here... 
- [Once an API key is acquired, pass it in the `EtherscanAPI` constructor in `TokenGatedChatUseCase.swift:147`](https://github.com/LiveLike/engagement-sample-app/wiki/Token-Gated-Chat-Tutorial#etherscanapi)
- https://github.com/LiveLike/engagement-sample-app/wiki/Token-Gated-Chat-Tutorial#3-query-the-blockchain

2022-06-01 14:32 UTC, mjelzon approved these changes

2022-06-01 14:33 UTC, merged